config/routes.rb
Sistemaescola::Application.routes.draw do
  resources :alunos

  resources :turmas

  resources :disciplinas

  resources :professors

  root :to => 'turmas#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
	belongs_to :turma
  	attr_accessible :age, :name, :turma_id
  	validates :name, :age, presence: true 
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
	belongs_to :professor
	has_many :disciplina_turma, dependent: :destroy
	has_many :turmas, through: :disciplina_turma
  	attr_accessible :name, :professor_id
  	validates :name, presence: true 
  	default_scope includes(:professor)
end

app/models/disciplina_turma.rb
class DisciplinaTurma < ActiveRecord::Base
  	belongs_to :disciplina
  	belongs_to :turma
  	validates :turma_id, :disciplina_id, presence: true 
end

app/models/professor.rb
class Professor < ActiveRecord::Base
	has_many :disciplinas, dependent: :destroy
  	attr_accessible :name, :age 
  	validates :name, :age, presence: true 
end

app/models/turma.rb
class Turma < ActiveRecord::Base
	has_many :alunos
	has_many :disciplina_turma, dependent: :destroy
	has_many :disciplinas, through: :disciplina_turma
  	attr_accessible :name
  	validates :name, presence: true 
  	default_scope includes([:disciplinas, :alunos])

  	def self.search(search)
	  if search && !search[:id].eql?('all')
	    includes(disciplinas: [:professor]).where(['turmas.name = ? or professors.name = ?', "#{search[:turma]}", "#{search[:professor]}"])
	  else
	    all
	  end
	end

end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  def index
    @alunos = Aluno.all
  end

  def show
    @aluno = get_aluno(params[:id])
  end

  def new
    @aluno = Aluno.new
  end

  def edit
    @aluno = get_aluno(params[:id])
  end

  def create
    @aluno = Aluno.new(params[:aluno])
    flash[:notice] = 'Aluno was successfully created.' if @aluno.save
    respond_with(@aluno)
  end

  def update
    @aluno = get_aluno(params[:id])
    flash[:notice] = 'Aluno was successfully updated.' if @aluno.update_attributes(params[:aluno])
    respond_with(@aluno)
  end

  def destroy
    @aluno = get_aluno(params[:id])
    flash[:notice] = 'Aluno was successfully deleted.' if @aluno.destroy
    respond_with(@aluno)
  end

  private
  def get_aluno(aluno_id)
    Aluno.find(aluno_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to :html, :json
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  def index
    @disciplinas = Disciplina.all
  end

  def show
    @disciplina = get_disciplina(params[:id])
  end

  def new
    @disciplina = Disciplina.new
  end

  def edit
    @disciplina = get_disciplina(params[:id])
  end

  def create
    @disciplina = Disciplina.new(params[:disciplina])
    flash[:notice] = 'Disciplina was successfully created.' if @disciplina.save
    respond_with(@disciplina)
  end

  def update
    @disciplina = get_disciplina(params[:id])
    flash[:notice] = 'Disciplina was successfully updated.' if @disciplina.update_attributes(params[:disciplina])
    respond_with(@disciplina)
  end

  def destroy
    @disciplina = get_disciplina(params[:id])
    flash[:notice] = 'Disciplina was successfully deleted.' if @disciplina.destroy
    respond_with(@disciplina)
  end

  private
  def get_disciplina(disciplina_id)
    Disciplina.find(disciplina_id)
  end

end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  def index
    @professors = Professor.all
  end

  def show
    @professor = get_professor(params[:id])
  end

  def new
    @professor = Professor.new
  end

  def edit
    @professor = get_professor(params[:id])
  end

  def create
    @professor = Professor.new(params[:professor])
    flash[:notice] = 'Professor was successfully created.' if @professor.save
    respond_with(@professor)
  end

  def update
    @professor = get_professor(params[:id])
    flash[:notice] = 'Professor was successfully updated.' if @professor.update_attributes(params[:professor])
    respond_with(@professor)
  end

  def destroy
    @professor = get_professor(params[:id])
    flash[:notice] = 'Professor was successfully deleted.' if @professor.destroy
    respond_with(@professor)
  end
  
  private
  def get_professor(professor_id)
    Professor.find(professor_id)
  end
  
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  def report
    @turmas = Turma.search(params)
  end

  def index
    @turmas = Turma.all
  end

  def show
    @turma = get_turma(params[:id])
  end

  def new
    @turma = Turma.new
  end

  def edit
    @turma = get_turma(params[:id])
  end

  def create
    @turma = Turma.new(params[:turma])
    if @turma.save
      params[:disciplinas][:id].each{ |id_disciplna| @turma.disciplinas.push(Disciplina.find(id_disciplna)) }
      flash[:notice] = 'Turma was successfully created.'
    end    
    respond_with(@turma)
  end

  def update
    @turma = get_turma(params[:id])
    
    if @turma.update_attributes(params[:turma])
      @turma_disciplinas = @turma.disciplinas

      found_ids = []
      @turma_disciplinas.find_each{ |ids_disciplina| found_ids.push(ids_disciplina.id) } 
      params[:disciplinas][:id].each{ |id_disciplina| found_ids.include?(id_disciplina.to_i) ? found_ids.delete(id_disciplina.to_i) : @turma_disciplinas.push(Disciplina.find(id_disciplina)) }

      found_ids.each do |ids_to_delete|
        @relation = @turma_disciplinas.find(ids_to_delete)
        @turma_disciplinas.delete(@relation)
      end

      flash[:notice] = 'Turma was successfully updated.' 
    end

    respond_with(@turma)
  end

  def destroy
    @turma = get_turma(params[:id])
    flash[:notice] = 'Turma was successfully deleted.' if @turma.destroy
    respond_with(@turma)
  end
  
  private

  def get_turma(turma_id)
    Turma.find(turma_id)
  end
  
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :turma %><br />
    <%= f.collection_select :turma_id, Turma.all, :id, :name, include_blank: "Selecione a Turma" %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing aluno</h1>

<%= render 'form' %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<h1>Listing alunos</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alunos.each do |aluno| %>
  <tr>
    <td><%= aluno.name %></td>
    <td><%= aluno.age %></td>
    <td><%= link_to 'Show', aluno %></td>
    <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
    <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New aluno</h1>

<%= render 'form' %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p>
  <b>Name:</b>
  <%= @aluno.name %>
</p>

<p>
  <b>Age:</b>
  <%= @aluno.age %>
</p>

<p>
  <b>Turma:</b>
  <%= @aluno.turma.name %>
</p>


<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/disciplinas/_form.html.erb
<%= form_for(@disciplina) do |f| %>
  <% if @disciplina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disciplina.errors.count, "error") %> prohibited this disciplina from being saved:</h2>

      <ul>
      <% @disciplina.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :professor %><br />
    <%= f.collection_select :professor_id, Professor.all, :id, :name, include_blank: "Selecione o Professor" %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/disciplinas/edit.html.erb
<h1>Editing disciplina</h1>

<%= render 'form' %>

<%= link_to 'Show', @disciplina %> |
<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/index.html.erb
<h1>Listing disciplinas</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Professor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disciplinas.each do |disciplina| %>
  <tr>
    <td><%= disciplina.name %></td>
    <td><%= disciplina.professor.name %></td>
    <td><%= link_to 'Show', disciplina %></td>
    <td><%= link_to 'Edit', edit_disciplina_path(disciplina) %></td>
    <td><%= link_to 'Destroy', disciplina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Disciplina', new_disciplina_path %>

app/views/disciplinas/new.html.erb
<h1>New disciplina</h1>

<%= render 'form' %>

<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/show.html.erb
<p>
  <b>Name:</b>
  <%= @disciplina.name %>
</p>

<p>
  <b>Professor:</b>
  <%= @disciplina.professor.name %>
</p>


<%= link_to 'Edit', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Back', disciplinas_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Sistemaescola", root_path, :class => 'brand' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sistemaescola" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sistemaescola" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <p>
            <br />
            <i>Sistema Escola - viniciustelesbezerra</i>
            <img src="https://pt.gravatar.com/userimage/40790479/156722cbc92bdf9fc167a1479c28f8d0.jpg" width="25" height="25" />
          </p>
          <%#= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <nav>
      <p>
        <ul class="nav nav-list">
          <li class="active">
            <a href="/turmas/report/all"><i class="icon-th-list"></i>Report</a>
          </li>
          <li>
            <a href="/turmas"><i class="icon-th-list"></i>Turmas</a>
          </li>
          <li>
            <a href="/disciplinas"><i class="icon-home icon-book"></i> Home - Disciplinas </a>
          </li>
          <li>
            <a href="/professors"><i class="icon-user icon-briefcase"></i>Professors</a>
          </li>
          <li>
            <a href="/alunos"><i class="icon-user"></i>Alunos</a>
          </li> 
        </ul>
      </p>
    </nav>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render 'form' %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<h1>Listing professors</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td><%= professor.name %></td>
    <td><%= professor.age %></td>
    <td><%= link_to 'Show', professor %></td>
    <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
    <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render 'form' %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p>
  <b>Name:</b>
  <%= @professor.name %>
</p>

<p>
  <b>Age:</b>
  <%= @professor.age %>
</p>


<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>

app/views/turmas/_form.html.erb
<%= form_for(@turma) do |f| %>
  <% if @turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% @turma.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <label>Disciplina - Professor</label> 
  <% Disciplina.find_each do |disciplina| %>
      <label>
        <%= check_box_tag 'disciplinas[id][]', disciplina.id, @turma.disciplinas.include?(disciplina) %>
        <%= disciplina.name %> - <%= disciplina.professor.name %>
      </label>
   <% end %>
  
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

  

app/views/turmas/edit.html.erb
<h1>Editing turma</h1>

<%= render 'form' %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<h1>Listing turmas</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
  </tr>

<% @turmas.each do |turma| %>

  <tr class="success">
    <td><%= turma.name %></td>
    <td><%= link_to 'Show', turma %></td>
    <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
    <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

  <tr>
    <th>Disciplinas</th>
  </tr>

  <tr class="info">
        <% turma.disciplinas.find_each do |disciplina| %>
        <td>
          <%= "#{disciplina.name} - #{disciplina.professor.name}" %>
        </td>
        <% end %>
  </tr>

<% end %>
</table>

<br />

<%= link_to 'New Turma', new_turma_path %>

app/views/turmas/new.html.erb
<h1>New turma</h1>

<%= render 'form' %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/report.html.erb
<h1>Report</h1>

<p>
  <%= form_tag '/turmas/report', method: 'post' do %>
      <label> Turma </label> <%= text_field_tag :turma, params[:turma] %> 
      <label> Professor </label> <%= text_field_tag :professor, params[:professor] %>
      <label> <%= submit_tag "Search", name: nil %> </label>
  <% end %>
</p>

<table class="table table-bordered">
  
<% @turmas.each do |turma| %>
  <tr>
    <th>Turma Name</th>
  </tr>

  <tr class="success">
    <td><%= turma.name %></td>
    <td><%= link_to 'Show', turma %></td>
  </tr>

  <tr>
    <th>Disciplinas</th>
  </tr>

  <tr class="info">
        <% turma.disciplinas.find_each do |disciplina| %>
        <td>
          <%= "#{disciplina.name} - #{disciplina.professor.name}" %>
        </td>
        <% end %>
  </tr>

  <tr>
    <th>Alunos</th>
  </tr>

  <tr class="error">
        <% turma.alunos.find_each do |aluno| %>
        <td>
          <%= aluno.name %>
        </td>
        <% end %>
  </tr>

<% end %>
</table>

app/views/turmas/show.html.erb
<p>
  <b>Name:</b>
  <%= @turma.name %>
</p>

<p>
  <b>Nome disciplina:</b>
  <% @turma.disciplinas.find_each do |disciplina| %>
    <%= disciplina.name %>
  <% end %>
</p>


<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>